---
title: "IButton Aug3"
output:
  pdf_document: default
  html_document: default
date: "2023-08-01"
---

# Section 1: K-Mean Cluster Analysis (centroid)

```{r, include=FALSE,echo=FALSE}
library(tidyverse)
library(cluster)
library(factoextra)
library(proxy)
library(tidyverse)
library(broom)
library(survey)
library(ggpubr) 
library(ggrepel) 
library(plotrix)
library(knitr)
library(patchwork)
library(pander)
library(gt)
library(readxl)
library(sjPlot)
library(haven)
library(readr)
library(ggplot2)
library(dplyr)
```

## BlockCentroid
```{r}
mydata <- read_excel("~/R/Aug8BlockOldData.xlsx")
mydata$ID <- as.character(mydata$ID)
str(mydata)
mydata <- as.data.frame(mydata)
rownames(mydata) <- c(mydata$ID)
head(mydata)
mydata <- na.omit(mydata)
mydata <- mydata[,-1]
mydata <- scale(mydata)
```
```{r, include=FALSE,echo=FALSE}
distance <- get_dist(mydata)
view<-fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
view
#fviz_dist: for visualizing a distance matrix
```
Here will group the data into three clusters:
```{r}
k2 <- kmeans(mydata, centers = 4, nstart = 100)
str(k2)
fviz_cluster(k2, data = mydata)
```

```{r}
cluster_assignments1 <- k2$cluster

# Add the cluster assignments to your original data frame
mydata_with_clusters1 <- cbind(mydata, Cluster = cluster_assignments1)

print(mydata_with_clusters1)

# Save the table to a CSV file
write.csv(mydata_with_clusters1, "blockclusters.csv", row.names = FALSE)
```

## 100M Centroid Cluster
```{r}
bufferdata<-read_excel("100mAug8.xlsx")
bufferdata$ID <- as.character(bufferdata$ID)
str(bufferdata)
bufferdata <- as.data.frame(bufferdata)
rownames(bufferdata) <- c(bufferdata$ID)
head(bufferdata)
bufferdata <- na.omit(bufferdata)
bufferdata <- bufferdata[,-1]
bufferdata <- scale(bufferdata)
```
```{r}
distance <- get_dist(bufferdata)
look<-fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
look
```
```{r}
k3 <- kmeans(bufferdata, centers = 4, nstart = 100)
str(k3)
fviz_cluster(k3, data = bufferdata)
```
```{r}
cluster_data2 <- k3$cluster

# Add the cluster assignments to your original data frame
centdata_with_clusters2 <- cbind(bufferdata, Cluster = cluster_data2)

print(centdata_with_clusters2)

# Save the table to a CSV file
write.csv(centdata_with_clusters2, "100mbufferclusters.csv", row.names = FALSE)
```

```{r}
new100data <- read_excel("Aug8New100Set.xlsx")
new100data$ID <- as.character(new100data$ID)
str(new100data)
new100data <- as.data.frame(new100data)
rownames(new100data) <- c(new100data$ID)
head(new100data)
new100data <- na.omit(new100data)
new100data <- new100data[,-1]
new100data <- scale(new100data)

```
```{r}
distance <- get_dist(new100data)
look<-fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
look

k4 <- kmeans(new100data, centers = 4, nstart = 100)
str(k4)
fviz_cluster(k4, data = new100data)

cluster_data4 <- k4$cluster

# Add the cluster assignments to your original data frame
centdata_with_clusters4 <- cbind(new100data, Cluster = cluster_data4)

print(centdata_with_clusters4)

# Save the table to a CSV file
write.csv(centdata_with_clusters4, "100mnewclusters.csv", row.names = FALSE)
```
```{r}
newblockdata <- read_excel("Aug8BlockNewData.xlsx")
newblockdata$ID <- as.character(newblockdata$ID)
str(newblockdata)
newblockdata <- as.data.frame(newblockdata)
rownames(newblockdata) <- c(newblockdata$ID)
head(newblockdata)
newblockdata <- na.omit(newblockdata)
newblockdata <- newblockdata[,-1]
newblockdata <- scale(newblockdata)
```
```{r}
distance5 <- get_dist(newblockdata)
look<-fviz_dist(distance5, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
look

k5 <- kmeans(newblockdata, centers = 4, nstart = 100)
str(k5)
fviz_cluster(k5, data = newblockdata)

cluster_data5 <- k5$cluster

# Add the cluster assignments to your original data frame
centdata_with_clusters5 <- cbind(newblockdata, Cluster = cluster_data5)

print(centdata_with_clusters5)

# Save the table to a CSV file
write.csv(centdata_with_clusters5, "newblockclusters.csv", row.names = FALSE)
```
```{r}
wssplot1 <- function(mydata, nc=4, seed=123){
               wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
               for (i in 2:nc){
                    set.seed(seed)
                    wss[i] <- sum(kmeans(mydata, centers=i)$withinss)}
                plot(1:nc, wss, type="b", xlab="Number of groups",
                     ylab="Sum of squares within a group")}

wssplot1(mydata,nc = 25,seed=123)


wssplot2 <- function(bufferdata, nc=4, seed=123){
               wss <- (nrow(bufferdata)-1)*sum(apply(bufferdata,2,var))
               for (i in 2:nc){
                    set.seed(seed)
                    wss[i] <- sum(kmeans(bufferdata, centers=i)$withinss)}
                plot(1:nc, wss, type="b", xlab="Number of groups",
                     ylab="Sum of squares within a group")}

wssplot2(bufferdata,nc = 25,seed=123)


wssplot3 <- function(new100data, nc=4, seed=123){
               wss <- (nrow(new100data)-1)*sum(apply(new100data,2,var))
               for (i in 2:nc){
                    set.seed(seed)
                    wss[i] <- sum(kmeans(new100data, centers=i)$withinss)}
                plot(1:nc, wss, type="b", xlab="Number of groups",
                     ylab="Sum of squares within a group")}

wssplot3(new100data,nc = 25,seed=123)


wssplot4 <- function(newblockdata, nc=4, seed=123){
               wss <- (nrow(newblockdata)-1)*sum(apply(newblockdata,2,var))
               for (i in 2:nc){
                    set.seed(seed)
                    wss[i] <- sum(kmeans(newblockdata, centers=i)$withinss)}
                plot(1:nc, wss, type="b", xlab="Number of groups",
                     ylab="Sum of squares within a group")}

wssplot4(newblockdata,nc = 25,seed=123)
```

```{r}
library(corrr)
library(ggcorrplot)
corr_matrix <- cor(newblockdata)
ggcorrplot(corr_matrix)
```
```{r}
library(GGally)
library(plotly)

p <- ggparcoord(data = mydata_with_clusters1, groupColumn = "Cluster", scale = "std") +
     labs(x = "predictor variables", y = "value (in standard-deviation units)", title = "Clustering for original blockmean")

ggplotly(p)

```
```{r}
p <- ggparcoord(data = centdata_with_clusters2, groupColumn = "Cluster", scale = "std") +
     labs(x = "predictor variables", y = "value (in standard-deviation units)", title = "Clustering for original 100mcentroid")

ggplotly(p)
```

```{r}
p <- ggparcoord(data = centdata_with_clusters4, groupColumn = "Cluster", scale = "std") +
     labs(x = "predictor variables", y = "value (in standard-deviation units)", title = "Clustering for new 100m centroid")

ggplotly(p)
```


```{r}

p <- ggparcoord(data = centdata_with_clusters5, groupColumn = "Cluster", scale = "std") +
     labs(x = "predictor variables", y = "value (in standard-deviation units)", title = "Clustering for newblockmean")

ggplotly(p)
```


